#!/bin/bash
# Fetches uBlock Origin Lite's prebuilt scriptlet bundles (the page scripts that handle what a URL
# rule can't, such as YouTube's in-player ads) for the same lists as Resources/blocklist.lzfse:
# uBlock filters and EasyPrivacy. EasyList has none. Each bundle carries its own hostname table and
# only runs the scriptlets meant for the page it's in, so Brook injects them into every frame.
#   Resources/scriptlets-main.js      page world (patches the page's own JS: fetch, XHR, JSON, ...)
#   Resources/scriptlets-isolated.js  Brook's own world (DOM, cookies, storage)
# uBOL is GPLv3 (github.com/uBlockOrigin/uBOL-home), like Brook.
set -euo pipefail
cd "$(dirname "$0")/.."

WORK=build/scriptlets
rm -rf "$WORK" && mkdir -p "$WORK"
# gh authenticates (GH_TOKEN in CI): the anonymous API is rate-limited per IP, and CI runners share IPs.
gh release download -R uBlockOrigin/uBOL-home -p '*.safari.zip' -D "$WORK"
zip=$(ls "$WORK"/*.safari.zip)
unzip -q "$zip" 'rulesets/scripting/scriptlet/*' -d "$WORK"

for world in main isolated; do
    out=Resources/scriptlets-$world.js
    echo "// uBlock Origin Lite scriptlets ($(basename "$zip" .safari.zip)), $world world. Generated by scripts/scriptlets.sh." > "$out"
    for list in ublock-filters easyprivacy; do
        f="$WORK/rulesets/scripting/scriptlet/$world/$list.js"
        if [ -f "$f" ]; then cat "$f" >> "$out"; echo >> "$out"; fi
    done
    echo "$(wc -c < "$out" | tr -d ' ') bytes -> $out"
done
